name: deploy-marketing

on:
  push:
    branches:
      - main
    paths:
      - 'packages/marketing/**'
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  reusableWorkflowMicrofrontendDeploy:
    uses: sargalias/microfrontends-example/.github/workflows/microfrontendDeploy.yml@main
    with:
      WORKING_DIRECTORY: packages/marketing
      APP_DEPLOY_DIRECTORY: /marketing/latest
      INVALIDATION_PATH: /marketing/latest/remoteEntry.js
    secrets:
      DOMAIN: ${{ secrets.DOMAIN }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
